# Generated by Django 4.2.5 on 2023-10-21 21:03

import base.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', base.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=12)),
                ('user_image', models.ImageField(default='', upload_to=base.models.upload_to)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='phone number should exactly be in 10 digits', regex='^\\d{10}$')])),
                ('house', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('town', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user_choices', models.TextField(blank=True, choices=[('employee', 'Employee'), ('sub_employee', 'Sub-employee'), ('baseUser', 'User')], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Headset', 'Headset'), ('Laptop', 'Laptop'), ('Mixer', 'Mixer'), ('Refrigerator', 'Refrigerator'), ('Speaker', 'Speaker'), ('Television', 'Television'), ('Washing Machine', 'Washing Machine')], default='', max_length=20, null=True)),
                ('condition', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Worst', 'Worst')], default='', max_length=20, null=True)),
                ('metal_quantity', models.JSONField(blank=True, default=str, null=True)),
                ('coins', models.IntegerField(blank=True, default=0, null=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to=base.models.uploadproduct)),
                ('status', models.CharField(blank=True, choices=[('None', 'None'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('orderno', models.CharField(blank=True, default=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
