# Generated by Django 4.2.5 on 2023-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='transaction_no',
            field=models.CharField(blank=True, default=True, max_length=30, null=True),
        ),
    ]
