# Generated by Django 4.2.5 on 2023-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userproducts_transaction_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='orderno',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='transaction_no',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
