# Generated by Django 5.0 on 2023-12-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(upload_to='backend'),
        ),
    ]
