# Generated by Django 5.0 on 2024-01-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_education_created_on_alter_education_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(null=True, upload_to='backend'),
        ),
    ]
