# Generated by Django 5.0 on 2024-01-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_education_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='backend'),
        ),
    ]
