# Generated by Django 5.0 on 2024-01-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_education_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('loction', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='events')),
                ('about', models.CharField(max_length=100)),
                ('cast_image1', models.ImageField(blank=True, default='', null=True, upload_to='events/cast')),
                ('cast_image2', models.ImageField(blank=True, default='', null=True, upload_to='events/cast')),
                ('cast_image3', models.ImageField(blank=True, default='', null=True, upload_to='events/cast')),
                ('cast_image4', models.ImageField(blank=True, default='', null=True, upload_to='events/cast')),
                ('cast_image5', models.ImageField(blank=True, default='', null=True, upload_to='events/cast')),
                ('cast_image6', models.ImageField(blank=True, default='', null=True, upload_to='events/cast')),
                ('cast_image7', models.ImageField(blank=True, default='', null=True, upload_to='events/cast')),
            ],
        ),
    ]
