# Generated by Django 5.0 on 2024-01-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_loction_eventcard_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='cast_image1',
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='cast_image2',
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='cast_image3',
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='cast_image4',
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='cast_image5',
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='cast_image6',
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='cast_image7',
        ),
        migrations.CreateModel(
            name='CastImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='events/cast')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_images', to='base.eventcard')),
            ],
        ),
    ]
