# Generated by Django 5.0 on 2024-01-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_eventcard_cast_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='content',
        ),
        migrations.AddField(
            model_name='education',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='content3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='content4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='content5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='content6',
            field=models.TextField(blank=True),
        ),
    ]
