# Generated by Django 5.0 on 2024-03-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_eventregistration_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event_name',
        ),
    ]
