# Generated by Django 4.2.5 on 2024-04-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_coupon_couponredemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.CharField(max_length=10),
        ),
    ]
