# Generated by Django 4.2.5 on 2024-04-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
