# Generated by Django 4.2.5 on 2024-04-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponredemption',
            unique_together={('coupon', 'user')},
        ),
    ]
