# Generated by Django 4.2.5 on 2024-04-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_couponredemption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coupon'),
        ),
    ]
