# Generated by Django 4.2.5 on 2024-04-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_transaction_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.BooleanField(default=True),
        ),
    ]
